"""change_recording_id_to_string

Revision ID: 10daadc4d40c
Revises: 9ca9cd81c77b
Create Date: 2024-12-30 01:45:00.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10daadc4d40c'
down_revision = '9ca9cd81c77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Change recording_id from UUID to String
    op.alter_column('lessons', 'recording_id',
                    existing_type=postgresql.UUID(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Change recording_id from String back to UUID
    op.alter_column('lessons', 'recording_id',
                    existing_type=sa.String(),
                    type_=postgresql.UUID(),
                    existing_nullable=True)
    # ### end Alembic commands ###
