"""Add recording_id and transcript_id to lessons

Revision ID: c5201615a379
Revises: e2ba01d3ab64
Create Date: 2025-06-29 22:25:36.603238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5201615a379'
down_revision: Union[str, Sequence[str], None] = 'e2ba01d3ab64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
